INSERT INTO {{ table }} VALUES (1, 'Life Pebble', 1, 1, 'maxhp,10', 'X');
INSERT INTO {{ table }} VALUES (2, 'Life Stone', 10, 1, 'maxhp,25', 'X');
INSERT INTO {{ table }} VALUES (3, 'Life Rock', 25, 1, 'maxhp,50', 'X');
INSERT INTO {{ table }} VALUES (4, 'Magic Pebble', 1, 1, 'maxmp,10', 'X');
INSERT INTO {{ table }} VALUES (5, 'Magic Stone', 10, 1, 'maxmp,25', 'X');
INSERT INTO {{ table }} VALUES (6, 'Magic Rock', 25, 1, 'maxmp,50', 'X');
INSERT INTO {{ table }} VALUES (7, 'Dragon\'s Scale', 10, 1, 'defensepower,25', 'X');
INSERT INTO {{ table }} VALUES (8, 'Dragon\'s Plate', 30, 1, 'defensepower,50', 'X');
INSERT INTO {{ table }} VALUES (9, 'Dragon\'s Claw', 10, 1, 'attackpower,25', 'X');
INSERT INTO {{ table }} VALUES (10, 'Dragon\'s Tooth', 30, 1, 'attackpower,50', 'X');
INSERT INTO {{ table }} VALUES (11, 'Dragon\'s Tear', 35, 1, 'strength,50', 'X');
INSERT INTO {{ table }} VALUES (12, 'Dragon\'s Wing', 35, 1, 'dexterity,50', 'X');
INSERT INTO {{ table }} VALUES (13, 'Demon\'s Sin', 35, 1, 'maxhp,-50', 'strength,50');
INSERT INTO {{ table }} VALUES (14, 'Demon\'s Fall', 35, 1, 'maxmp,-50', 'strength,50');
INSERT INTO {{ table }} VALUES (15, 'Demon\'s Lie', 45, 1, 'maxhp,-100', 'strength,100');
INSERT INTO {{ table }} VALUES (16, 'Demon\'s Hate', 45, 1, 'maxmp,-100', 'strength,100');
INSERT INTO {{ table }} VALUES (17, 'Angel\'s Joy', 25, 1, 'maxhp,25', 'strength,25');
INSERT INTO {{ table }} VALUES (18, 'Angel\'s Rise', 30, 1, 'maxhp,50', 'strength,50');
INSERT INTO {{ table }} VALUES (19, 'Angel\'s Truth', 35, 1, 'maxhp,75', 'strength,75');
INSERT INTO {{ table }} VALUES (20, 'Angel\'s Love', 40, 1, 'maxhp,100', 'strength,100');
INSERT INTO {{ table }} VALUES (21, 'Seraph\'s Joy', 25, 1, 'maxmp,25', 'dexterity,25');
INSERT INTO {{ table }} VALUES (22, 'Seraph\'s Rise', 30, 1, 'maxmp,50', 'dexterity,50');
INSERT INTO {{ table }} VALUES (23, 'Seraph\'s Truth', 35, 1, 'maxmp,75', 'dexterity,75');
INSERT INTO {{ table }} VALUES (24, 'Seraph\'s Love', 40, 1, 'maxmp,100', 'dexterity,100');
INSERT INTO {{ table }} VALUES (25, 'Ruby', 50, 1, 'maxhp,150', 'X');
INSERT INTO {{ table }} VALUES (26, 'Pearl', 50, 1, 'maxmp,150', 'X');
INSERT INTO {{ table }} VALUES (27, 'Emerald', 50, 1, 'strength,150', 'X');
INSERT INTO {{ table }} VALUES (28, 'Topaz', 50, 1, 'dexterity,150', 'X');
INSERT INTO {{ table }} VALUES (29, 'Obsidian', 50, 1, 'attackpower,150', 'X');
INSERT INTO {{ table }} VALUES (30, 'Diamond', 50, 1, 'defensepower,150', 'X');
INSERT INTO {{ table }} VALUES (31, 'Memory Drop', 5, 1, 'expbonus,10', 'X');
INSERT INTO {{ table }} VALUES (32, 'Fortune Drop', 5, 1, 'goldbonus,10', 'X');